spring:
  profiles:
    active: db, core, admin
  messages:
    encoding: UTF-8

server:
  port: 10089

logging:
  level:
    root:  ERROR
    org.springframework:  ERROR
    org.mybatis:  ERROR
    com.goodstuff.mall.admin:  DEBUG
    com.goodstuff.mall:  ERROR